name: zEssentials
version: ${version}
main: fr.maxlego08.essentials.ZEssentialsPlugin
folia-supported: true
description: Provides an essential, core set of commands for Bukkit.
website: https://groupez.dev/
author: [ YanIanZ ]
contributors: [ Maxlego08, Louis_Dew, Traqueur, JavaToastDev, Melon-Oof, alwyn974, Mapacheee, NeiiZun, groundbreakingmc ]
softdepend:
  - zMenu
  - PlaceholderAPI
  - Vault
  - ProtocolLib
  - SuperiorSkyblock2
  - BentoBox
api-version: '1.20'
libraries:
  - 'org.mariadb.jdbc:mariadb-java-client:3.5.6'
  - 'org.mongodb:mongodb-driver-sync:5.2.1'
